apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
  labels:
    app: time-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-app
  template:
    metadata:
      labels:
        app: time-app
    spec:
      containers:
      - name: time-app-container
        image: time:v1 
        ports:
        - containerPort: 80

