all:
  hosts:
    remote_host:
      ansible_host: 192.168.24.134
      ansible_user: sambath
      ansible_ssh_private_key_file: /home/sambath/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3  
